name: Notify on Branch Push

on:
  push:
    branches:
      - '*'  # 监听所有分支的推送事件

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send notification to WeChat
      run: |
        curl -X POST "${{ secrets.WECHAT_WEBHOOK_URL }}" \
        -H "Content-Type: application/json" \
        -d '{
              "msgtype": "markdown",
              "markdown": {
                  "content": "**New push to branch:** <font color=\"info\">${{ github.ref }}</font>\n**Commit message:** <font color=\"info\">${{ github.event.head_commit.message }}</font>\n**Author:** <font color=\"info\">${{ github.event.head_commit.author.name }}</font>"
              }
          }'
